# Expérimentation de la méthode d'évaluation "Retrieval"

## Importation des bibliothèques

In [1]:
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
import numpy as np
import pytrec_eval
import json

c:\Users\lucas\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Chargement du corpus et du modèle

In [ ]:
newsgroups = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))
target = newsgroups.target
docs = newsgroups['data']

topic_model = BERTopic(calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)

[10  3 17 ...  3  1  7]

KeyboardInterrupt:

## Prise en main de BERTopic

In [3]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6634,-1_to_the_of_you,"[to, the, of, you, is, and, in, for, it, that]",[#In article <1r3tqo$ook@horus.ap.mchp.sni.de>...
1,0,1835,0_game_team_games_he,"[game, team, games, he, players, season, hocke...","[\n\n""Deeply rooted rivalry?"" Ahem, Jokerit ha..."
2,1,577,1_key_clipper_chip_encryption,"[key, clipper, chip, encryption, keys, escrow,...","[[An article from comp.org.eff.news, EFFector ..."
3,2,524,2_ites_cheek_yep_huh,"[ites, cheek, yep, huh, ken, why, each, of, , ]","[\nHuh?, \nYep.\n, \n \n ..."
4,3,469,3_israel_israeli_jews_arab,"[israel, israeli, jews, arab, jewish, arabs, p...",[Many of you ask me whether I approve of sever...
...,...,...,...,...,...
210,209,10,209_sound_mac_macrecorder_recorder,"[sound, mac, macrecorder, recorder, soundtool,...",[\n\n...\n\n\nMac sound hardware is diverse; s...
211,210,10,210_printer_postscript_print_file,"[printer, postscript, print, file, printouts, ...",[You CAN print to a file from an HP (or any ot...
212,211,10,211_beauchaine_bobbeviceicotekcom_sank_bronx,"[beauchaine, bobbeviceicotekcom, sank, bronx, ...",[\n Do I smell .sig material here?\n\n\n/\/\/...
213,212,10,212_stuffit_system_files_disk,"[stuffit, system, files, disk, macintosh, soft...",[\n\nplease tell me where you where you FTP'd ...
214,213,10,213_mischealthdiabetes_votes_pray_vote,"[mischealthdiabetes, votes, pray, vote, lunch,...",[I'm having trouble receiving News at the mome...

In [4]:
topic_model.get_topic(0)

[('game', np.float64(0.010398322569578738)),
 ('team', np.float64(0.009045119889402535)),
 ('games', np.float64(0.0072039344310178355)),
 ('he', np.float64(0.007105180576995655)),
 ('players', np.float64(0.0063379042786358645)),
 ('season', np.float64(0.006256397371611483)),
 ('hockey', np.float64(0.0061445977473780534)),
 ('play', np.float64(0.005792399279813237)),
 ('25', np.float64(0.005661857430114134)),
 ('year', np.float64(0.005636726725192117))]

In [5]:
topic_model.get_document_info(docs)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,\n\nI am sure some bashers of Pens fans are pr...,0,0_game_team_games_he,"[game, team, games, he, players, season, hocke...","[\n\n""Deeply rooted rivalry?"" Ahem, Jokerit ha...",game - team - games - he - players - season - ...,0.241062,False
1,My brother is in the market for a high-perform...,-1,-1_to_the_of_you,"[to, the, of, you, is, and, in, for, it, that]",[#In article <1r3tqo$ook@horus.ap.mchp.sni.de>...,to - the - of - you - is - and - in - for - it...,0.321072,False
2,\n\n\n\n\tFinally you said what you dream abou...,46,46_were_armenians_they_azerbaijan,"[were, armenians, they, azerbaijan, her, was, ...",[Accounts of Anti-Armenian Human Right Violati...,were - armenians - they - azerbaijan - her - w...,0.042489,False
3,\nThink!\n\nIt's the SCSI card doing the DMA t...,4,4_drive_scsi_drives_ide,"[drive, scsi, drives, ide, disk, controller, h...",[Thanks to all who responded to my original po...,drive - scsi - drives - ide - disk - controlle...,0.151164,False
4,1) I have an old Jasmine drive which I cann...,96,96_tape_backup_tapes_drive,"[tape, backup, tapes, drive, wangdat, munroe, ...",[I have a Colorado Memory Systems Jumbo 250 ta...,tape - backup - tapes - drive - wangdat - munr...,0.190094,False
...,...,...,...,...,...,...,...,...
18841,DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...,25,25_doctor_cancer_patients_medical,"[doctor, cancer, patients, medical, doctors, c...",[\n\nPoint 1:\n\nI'm beginning to see that *pa...,doctor - cancer - patients - medical - doctors...,0.231487,False
18842,\nNot in isolated ground recepticles (usually ...,-1,-1_to_the_of_you,"[to, the, of, you, is, and, in, for, it, that]",[#In article <1r3tqo$ook@horus.ap.mchp.sni.de>...,to - the - of - you - is - and - in - for - it...,0.052050,False
18843,I just installed a DX2-66 CPU in a clone mothe...,92,92_fan_cpu_heat_sink,"[fan, cpu, heat, sink, fans, cooling, chip, ho...","[N(P>Just got a 66MHz 486DX2 system, and am co...",fan - cpu - heat - sink - fans - cooling - chi...,1.000000,False
18844,\nWouldn't this require a hyper-sphere. In 3-...,19,19_den_polygon_points_algorithm,"[den, polygon, points, algorithm, xxxx, plane,...","[\nSorry!! :-)\n\nCall the four points A, B, C...",den - polygon - points - algorithm - xxxx - pl...,0.347380,False
18845,After a tip from Gary Crum (crum@fcom.cc.utah....,5,5_car_cars_engine_ford,"[car, cars, engine, ford, mustang, toyota, mil...","[\n\n*nnnnnnnng* Thank you for playing, I cann...",car - cars - engine - ford - mustang - toyota ...,1.000000,False

In [6]:
embedding = topic_model.embedding_model.embed_words([word for word, _ in topic_model.get_topic(0)])
embedding

array([[-0.05142733,  0.0636927 , -0.07169519, ...,  0.02179561,
        -0.06278875, -0.00463669],
       [-0.10208665,  0.02944556, -0.06223712, ...,  0.06445801,
         0.0095756 , -0.01843228],
       [-0.0103558 ,  0.01515841, -0.03154234, ..., -0.0016096 ,
        -0.04747131, -0.00085111],
       ...,
       [ 0.04348339, -0.03390434,  0.02455976, ...,  0.00742066,
         0.01485858,  0.02921391],
       [-0.00060689,  0.03807206, -0.07132157, ..., -0.05815599,
        -0.00622268, -0.01801906],
       [-0.04465517,  0.09486965, -0.01716308, ...,  0.0322977 ,
        -0.048214  ,  0.02786571]], shape=(10, 384), dtype=float32)

## Retrieval

In [7]:
topic_model.get_document_info(docs)['Representation'][0]

['game',
 'team',
 'games',
 'he',
 'players',
 'season',
 'hockey',
 'play',
 '25',
 'year']

In [8]:
def prepare_qrel(true_labels: np.ndarray) -> {}:
    """
    true_labels : Les vraies labels du dataset
    """
    
    qrel = {}
    for doc_idx, label in enumerate(true_labels):
        topic_id = str(label)
        doc_id = str(doc_idx)
        if topic_id not in qrel:
            qrel[topic_id] = {}
        qrel[topic_id][doc_id] = 1
    return qrel

In [9]:
def prepare_run(probs: np.ndarray) -> {}:
    """
    probs : La matrice de probabilités retournée par fit_transform
    """
    
    run = {}
    for topic_idx in range(probs.shape[1]):
        topic_id = str(topic_idx)
        run[topic_id] = {}
        for doc_idx in range(probs.shape[0]):
            doc_id = str(doc_idx)
            run[topic_id][doc_id] = float(probs[doc_idx, topic_idx])
    return run

In [ ]:
def retrieval(probs: np.ndarray, true_labels: np.ndarray) -> {}:
    """
    probs : La matrice de probabilités retournée par fit_transform
    true_labels : Les vraies labels du dataset
    """
    
    qrel = prepare_qrel(true_labels=true_labels)

    run = prepare_run(probs=probs)

    evaluator = pytrec_eval.RelevanceEvaluator(qrel, {'map', 'ndcg', 'P_5', 'recip_rank'}) # Rechercher quelles métriques calculer
    results = evaluator.evaluate(run)
    
    return results

In [16]:
eval = retrieval(topic_model=topic_model, probs=probs, true_labels=target)
print(json.dumps(eval, indent=1)) # Mise en forme json

{
 "0": {
  "map": 0.03065807985980056,
  "recip_rank": 0.0008319467554076539,
  "P_5": 0.0,
  "ndcg": 0.5816255323568567
 },
 "1": {
  "map": 0.03997964185730561,
  "recip_rank": 0.0024096385542168677,
  "P_5": 0.0,
  "ndcg": 0.6110320756941746
 },
 "2": {
  "map": 0.048726562752273876,
  "recip_rank": 0.5,
  "P_5": 0.2,
  "ndcg": 0.6422361032487728
 },
 "3": {
  "map": 0.036842906212538315,
  "recip_rank": 0.00035714285714285714,
  "P_5": 0.0,
  "ndcg": 0.6000837876009225
 },
 "4": {
  "map": 0.20538622063853254,
  "recip_rank": 0.3333333333333333,
  "P_5": 0.4,
  "ndcg": 0.7692967400813834
 },
 "5": {
  "map": 0.04117615235038453,
  "recip_rank": 0.0006574621959237344,
  "P_5": 0.0,
  "ndcg": 0.6098807403315514
 },
 "6": {
  "map": 0.22795382751396234,
  "recip_rank": 0.5,
  "P_5": 0.6,
  "ndcg": 0.7893483277236065
 },
 "7": {
  "map": 0.04945832351106338,
  "recip_rank": 0.06666666666666667,
  "P_5": 0.0,
  "ndcg": 0.6306544729888551
 },
 "8": {
  "map": 0.0395360349496507,
  "recip_rank": 0.0011248593925759281,
  "P_5": 0.0,
  "ndcg": 0.6066190309311141
 },
 "9": {
  "map": 0.06859678228072393,
  "recip_rank": 0.0019305019305019305,
  "P_5": 0.0,
  "ndcg": 0.6467896603770885
 },
 "10": {
  "map": 0.06984443092180773,
  "recip_rank": 0.005780346820809248,
  "P_5": 0.0,
  "ndcg": 0.6522770432590739
 },
 "11": {
  "map": 0.04733570897221926,
  "recip_rank": 0.0024691358024691358,
  "P_5": 0.0,
  "ndcg": 0.6206471782313722
 },
 "12": {
  "map": 0.0451336994446568,
  "recip_rank": 0.0018050541516245488,
  "P_5": 0.0,
  "ndcg": 0.6248194655136332
 },
 "13": {
  "map": 0.047609675710595975,
  "recip_rank": 0.3333333333333333,
  "P_5": 0.2,
  "ndcg": 0.6344783574226524
 },
 "14": {
  "map": 0.052143151301601284,
  "recip_rank": 0.0036231884057971015,
  "P_5": 0.0,
  "ndcg": 0.6344106902526259
 },
 "15": {
  "map": 0.0353358381848468,
  "recip_rank": 0.0008547008547008547,
  "P_5": 0.0,
  "ndcg": 0.5987911313125881
 },
 "16": {
  "map": 0.03357101125784356,
  "recip_rank": 0.0007598784194528875,
  "P_5": 0.0,
  "ndcg": 0.5897584048136691
 },
 "17": {
  "map": 0.09521271065783685,
  "recip_rank": 0.006666666666666667,
  "P_5": 0.0,
  "ndcg": 0.6804265285445275
 },
 "18": {
  "map": 0.04888893113709108,
  "recip_rank": 0.013157894736842105,
  "P_5": 0.0,
  "ndcg": 0.6241268731596009
 },
 "19": {
  "map": 0.022071449837182896,
  "recip_rank": 0.001392757660167131,
  "P_5": 0.0,
  "ndcg": 0.5464932313114773
 }
}